### ISSUE TITLE
\forall missing in operator list

### ISSUE THREAD

**Issue by david-christiansen** [jonsterling/JonPRL#114]
`jonprl --list-operators` doesn't include forall, presumably because it's an alias for dependent intersection.

**Comment by jozefg** [comment]
I think we got rid of \forall and now just have \bigcap so it shouldn't be in there?https://github.com/jonsterling/JonPRL/commit/1278a191c6a4796c50841ed63135f334b1595104

**Comment by david-christiansen** [comment]
Indeed! it was only one `M-x revert-buffer` away!

**Comment by jonsterling** [comment]
Sorry, I just sort of made that change without telling anyone! :)

I was seeing that everyone was using `\forall` instead of `\bigcap`, and I figured I should put a stop to it... (BTW, in case you're curious, we call what JonPRL has the "family intersection", and the "dependent intersection" is another very interesting type which we will want to add soon.)

**Comment by david-christiansen** [comment]
OK! The mode is hereby updated.
