### ISSUE TITLE
First-order matching

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#126]
One thing that would help proof automation in a huge way would be to support a very simple version of Coq's `match goal with` thing.

However, one wrinkle is that this probably involves changing the syntax of tactic scripts to use ABTs, since we will now be binding (meta)variables for hypothesis labels, etc. @jozefg, any thoughts? Is there a simple way we can do this?

**Comment by jozefg** [comment]
Hm, this is going to be a bother because I suspect we won't be able to use `sml-abt`: it's hitting that pathalogical case of binding variables in one sort that range over a different sort, in this case tactics binding terms.. So we'll have to handwrite some of the binding if we go that route.

Otherwise we we need to write some tactic of the form

```
 match (x.y.z. ... [term] [term] ... [term] {tactic})
```

Where `x`, `y` and `z` range over terms and may occur freely in any of the terms or tactic arbitrarily. Then the behaviour is that when run on a goal we match the first `n - 1` terms to some hypotheses and the last one to the goal, unifying the free variables `x`, `y`, and `z` as it goes. Have I got that all right?

This will be pretty complicated it would seem!
