### ISSUE TITLE
custom prefix, infix & postfix operator notations

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#143]
The stage is set for relatively painless declarations of custom prefix, infix and postfix operators in JonPRL developments; mixfix would be much harder, and I'm not (personally) interested in pursuing it.

I want to treat these as notations, not as definitions. So, something like this might happen:

``` jonprl
Operator Tensor : (0;0).
Infix Right 7 <⊗> := <Tensor>.

Operator Bang : (0).
Postfix 8 <!> := <Bang>.
```

**Comment by ghost** [comment]
This would be a really nice improvement. I also feel the same way about mixfix: it's not worth the effort and probably wouldn't be the right choice even if it were easy to implement (and for that amount of effort I'd rather have a macro system or something).

**Comment by ghost** [comment]
It may be out of scope for this PR but one thing I'd like to have with operators is sectioning with positional wildcards somehow. This would help with category theory developments where I otherwise need to define multiple versions of the same operator where one has the arguments flipped or duplicated.

I'm thinking of something like this:

```
(A ⊗ ?) | 0:_
==> (A ⊗ ?y\y) | 0:y (y fresh)
==> (A ⊗ y) [y/y] | 0:y
==> lam(y. A ⊗ y)

(? ⊗ B) | 0:_
==> (?x\x ⊗ B) | 0:x (x fresh)
==> (x ⊗ B) [x/x] | 0:x
==> lam(x. x ⊗ B)

(? ⊗ ?) | 0:_, | 1:_
==> (?x\x ⊗ ?) | 0:x, 1:_ (x fresh)
==> (x ⊗ ?) [x/x] | 0:x, 1:_
==> (x ⊗ ?y\y) [x/x] | 0:x, 1:y (y fresh)
==> (x ⊗ y) [x/x; y/y] | 0:x, 1:y
==> lam(x. lam(y. x ⊗ y))

(?x ⊗ ?\x) | 0:x, 1:_
==> (?x\x ⊗ ?\x) | 0:x, 1:_
==> (x ⊗ ?\x) [x/x] | 0:x, 1:_
==> (x ⊗ ?y\x) [x/x] | 0:x, 1:y (y fresh)
==> (x ⊗ ?y\x) [x/x, x/y] | 0:x, 1:y
==> (x ⊗ y) [x/{x, y}] | 0:x, 1:y (sort/group by replacer)
==> lam(x. x ⊗ x)

(?x\y ⊗ ?y\x) | 0:x, 1:y
==> (x ⊗ ?y\x) [y/x] | 0:x, 1:y
==> (x ⊗ y) [y/x; x/y] | 0:x, 1:y
==> (x ⊗ y) [x/y; y/x] | 0:x, 1:y (sort/group by replacer)
==> lam(x. lam(y. y ⊗ x))
```

The syntax is `QUESTION_MARK {position}? {\ replacer}?` where both names are optional. This specifies a simultaneous substitution where the position names have an implicit order. When `replacer` is not given the substitution is the identity. Read `x\y` as "y replaces x" and `x/{y_0, …, y_n}` as "bind x, replacing y_0, …, y_n". You probably want to use a map or hash table to avoid the need to explicitly do the sorting/grouping at the end.

**Comment by jonsterling** [comment]
That's be really cool! The first two would probably be very easy to implement, and the last one may need some deliberation...

**Comment by ghost** [comment]
I updated the example syntax and explanation to be a little more concrete. I think if you have some way of keeping track of substitutions while manipulating the terms it shouldn't be too difficult to implement. Whether it's a good idea is another issue I guess.

**Comment by david-christiansen** [comment]
It's getting to the point where some sort of agda-mode-like highlighting would be good to support in Emacs :)
