### ISSUE TITLE
README with instructions for building

### ISSUE THREAD

**Issue by david-christiansen** [jonsterling/JonPRL#15]
It would be nice if there were a 1-paragraph README explaining compatibility with SML implementations and with basic instructions for building and running JonPRL - the interaction model is a bit different that most systems, and it's hard to know where to start.

**Comment by jonsterling** [comment]
Yes, you are definitely right; was discussing this with Darin yesterday as well... I have so far held off on writing instructions for setup & installation since it was all in a bit of flux, but now is probably the time.

Re "running JonPRL", the interaction model is indeed a bit different, though I would prefer say that the interaction model is simply not present. All there is right now is the ability to use JonPRL as a library, and execute tactic scripts; it turns out to actually be pretty "interactive" by coincidence (when your script fails, it throws an exception that contains the error or remaining subgoals), but this is not the intended interaction model...

My "Step 1" goal is to provide a top-level interface like `coqtop` or `cochon` from Epigram 2; after this, other interaction models may be explored, but something along these lines might initially serve as the basis for other tools, such as an emacs or vi mode, etc.

**Comment by jonsterling** [comment]
I have added a README with rudimentary build instructions.

**Comment by jonsterling** [comment]
I also added discussion of the historical context of JonPRL, Nuprl, and made some clarifying remarks about "extensional type theory", "computational type theory" and the "proof refinement logic" (and included my usual clarification of "equality reflection").

**Comment by david-christiansen** [comment]
This is great! Thanks! I look forward to playing with it when I get a bit of time.

It might be nice to introduce your syntax earlier in the README, e.g. "`H >>> J` is a sequent".
