### ISSUE TITLE
Nuprl-style equality type

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#161]
At OPLSS, Bob Constable talked about how Nuprl's equality type has different well-formedness conditions than it used to, such that it can be well-formed even in case the equands are not of the right type. I seem to recall that this used intersection and top or base or something, but I can't quite remember.

@vrahli Do you have any comment?

**Comment by vrahli** [comment]
The rule uses the union type.  In Nuprl, we actually use the image type
directly because
the union type is defined in terms of the image type.
Now the rule says that to prove (a1 = a2 in A) = (b1 = b2 in B) in U(i),
you have to prove that a1 = b1 in (A union Base) and (a2 = b2 in A union
Base),
which among other things means that to prove that (t in T) in U(i), it's
enough to
prove that (t in base) and (T in U(i)).  That means that now we can prove
not(U(i) in (U(i))
because (U(i) in U(i)) is well-formed.  Also we can now define A subtype B
as
\x.x in (A -> B).

Does that make sense?

On Sun, Jul 26, 2015 at 2:26 PM, Jonathan Sterling <notifications@github.com

> wrote:
> 
> At OPLSS, Bob Constable talked about how Nuprl's equality type has
> different well-formedness conditions than it used to, such that it can be
> well-formed even in case the equands are not of the right type. I seem to
> recall that this used intersection and top, but I can't quite remember.
> 
> @vrahli https://github.com/vrahli Do you have any comment?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jonsterling/JonPRL/issues/161.

## 

http://www.cs.cornell.edu/~rahli/

**Comment by jonsterling** [comment]
OK, very interesting, thanks!

Initially, one thing that worried me about this rule is that it felt impredicative or non-wellfounded—I'm not sure how to put my suspicion into words though. Does this make sense, or is my concern unfounded?

**Comment by vrahli** [comment]
The issue with the old rule is that it's what we call a non-negatable
proposition.
I think Karl Crary, among others, talks about this issue (negatability) in
his thesis.

On Mon, Jul 27, 2015 at 12:11 PM, Jonathan Sterling <
notifications@github.com> wrote:

> OK, very interesting, thanks!
> 
> Initially, one thing that worried me about this rule is that it felt
> impredicative or non-wellfounded—I'm not sure how to put my suspicion into
> words though. Does this make sense, or is my concern unfounded?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jonsterling/JonPRL/issues/161#issuecomment-125259081.

## 

http://www.cs.cornell.edu/~rahli/

**Comment by jonsterling** [comment]
Closed by #187
