### ISSUE TITLE
use a better data structure for subgoals

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#2]
the kinds of computations I'm needing to do on subgoals are probably not well-suited to lists. perhaps concatenable deques might be a better option.

**Comment by ghost** [comment]
Out of curiosity, what kind of properties do you need the structures to have? Zippers and/or finger trees might be worth exploring. For shoggoth I was using defunctionalized difference lists with zippers for the type lens stuff since it was fairly low effort and still better than just lists. For something more ephemeral, the [chunked sequences](http://deepsea.inria.fr/chunkedseq/) stuff is worth a look I think. They had an OCaml implementation floating around but I could never find it. IIRC, they use some techniques that let them implement finger-tree like structures, but in an imperative setting with ephemeral buffers, giving them better constant factors due to data-locality/cache behavior, etc. (I think some of Kmett's recent cache-oblivious stuff may be better in that regard too but I haven't looked at it).

**Comment by jonsterling** [comment]
Interesting! I'm going to hold off on addressing this until/if I start experiencing performance problems. I have already replaced core tactics with a cleaner, probably more efficient implementation, but I anticipate that I may want to revisit the data structures & algorithms at a later time.

**Comment by jonsterling** [comment]
closing because it belongs on the `sml-lcf` repo
