### ISSUE TITLE
Defined operators of arbitrary arity

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#51]
Right now, definitions are limited to being nullary (and references to a defined term are treated as free variables). It would be better if we added a special operator that took a symbol as its _parameter_, and then considered the parsing of ABTs as parameterized over a development. Then, something like this would be possible:

```
operator times : (0,0).
times(A; B) =def= sigma(A; x. B)

operator exists : (0,1).
exists(A; x. B) =def= sigma(A; x. B)
```

Now, Nuprl does this but has special "second order variables", as in `exists(A; x. B[x]) =def= sigma(A; x. B[x])`, but I don't know if that is necessary here. Any thoughts?

(We're currently getting around the lack of this facility by defining things as lambda terms, but that is not really ideal.)

**Comment by ghost** [comment]
It would be really nice to have this. Not sure about the "second order variables" though. Is there a reference somewhere that describes them?

Actually I've been wondering about whether it could make sense to try and implement multi-abstraction/application like in the setoid thing we worked on. In the most general sense (with respect to polynomial monads) there are some difficult issues to figure out, but for lists it _seems_ like it shouldn't be that hard, especially in this setting. I tried out two different versions of that with Shoggoth. The first one had a fancier kind system but the second one basically just used arities.

I could try to write up some rules if you think it might be feasible to implement here.

**Comment by jonsterling** [comment]
This chapter of the Nuprl manual discusses second order variables & subsitutions: http://www.nuprl.org/html/02cucs-NuprlManual-07definition.pdf

Sure, I'd be interested to see what you have in mind for "multi-abstraction". I guess in this setting, it would mean an more advanced structure for arities than just lists of valences?

**Comment by ghost** [comment]
Okay, I'll try and write something up about what I have in mind. What I had for shoggoth was a little bit like what you've written above in that you always gave an operator with an arity and this information was used during "inference" and normalization. I think the encoding I used for arities was equivalent to hereditarily finite sets (or rose trees of unit). You can interpret these as numbers in the usual way but the ordering is important here whereas it isn't in sets:

```
data HFS = T [HFS] -- the T will be implicit below

zero : []
succ : [[]]
add : [[], []]
map : [[[]], []]
```

The way I imagined this would work is you would generalize lambda to abstract over many variables. Pair would be n-ary instead of binary, which I guess would make Sigma more like records. (The argument to a multi-function was always a list and convenience types were provided for the unary case.) Unit would become redundant in this setting too. It probably makes sense to provide multi-composition as a builtin thing but maybe it could be defined. Anyway, it might be too radical but it would certainly make the scripts a lot nicer since we could get rid of these big nested blocks of `ap`. In fact, the reason I considered this approach for shoggoth was for precisely the same reason IIRC.

**Comment by jonsterling** [comment]
Interesting... If you wish to pursue this, then I think it basically
amounts to a generalization of abstract binding trees. This would be
very, very useful! If you can make the rules clear, than we can probably
implement a generalized version of the `abt` library.

However, I just want to note that with the current version of arities,
the mess of ap(ap(ap(.... is also resolved. I think that your proposed
structure would simply give a more general/unified treatment of
operators & their bindings, where you no longer need the separation
between "arity" and "valence", I think.

JMS
