### ISSUE TITLE
add prelude, remove built-in MEM operator

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/JonPRL#55]
A prelude should include at least the following (this requires #54 to be implemented):

```
Operator ∈ : (0;0).
[∈(M;A)] =def= [=(M;M;A)].

Resource auto-unfold += { unfold <∈> }.
```

When running `jonprl`, the Prelude should be automatically prepended to the development, but there should be a `--no-prelude` flag that you can pass.

Open question: where should the prelude live? Should it just be baked into the binary? I want JonPRL to work immediately without a complicated installation process, and I really hate dealing with issues where some file was expected to exist in some location, but it does not.

**Comment by ghost** [comment]
As long as there is a `--no-prelude` flag it's probably okay to bake it into the binary at least in the short term. I tend to prefer to explicitly include prelude stuff though rather than having to disable it but maybe it's not a big deal. However, it might be a good idea to distinguish between some minimal set of builtin things and a prelude in the more traditional sense. For example, in purescript they've removed the prelude now and made it something you have to explicitly import. There is some very basic stuff included by default like number and array types but pretty much all of the things that can be defined (`($)`, etc.) are put into the prelude.

**Comment by jonsterling** [comment]
makes sense; i am thinking I just want a way to have certain ambient definitions that every development needs. probably this is different from a "prelude", which we may not even want. I like the purescript approach.
